### ISSUE TITLE
When will the site go live?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-event-landingpage#13]
## Your Question
See title, currently the page on https://e.coronawarn.app is not the same as the source code here. When will the "real" site go live?

**Comment by thomasaugsten** [comment]
We expect end of this week

**Comment by Ein-Tim** [comment]
Thank you. I'll leave this open until it's live.

**Comment by genericmueller** [comment]
I deployed it today. You can close this issue.

**Comment by Ein-Tim** [comment]
@genericmueller 

Thank you, I can confirm that the site is live!
