### ISSUE TITLE
Applinks will not work if the server side file is missing.

### ISSUE THREAD

**Issue by eilers** [corona-warn-app/cwa-event-landingpage#22]
## Problem with Applinks and Rapid-Tests
I really want to add a button on the booking page for adding a rapid test to the CWA. This is important if someone is booking the test online with its smartphone. He usually cannot print the code and scan it afterwards with the CWA.
But clicking on the link opens the Appstore and not the app.

## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: All
- iOS version: 14.5.1
- App version: 2.2.1

## Describe the bug
The application seems to correctly define the following domain `s.coronawarn.app` as *Accociated Domain*. But unfortunately this will not work until there is no server-side file called `apple-app-site-association` accessible via `https://s.coronawarn.app/apple-app-site-association`. I'm not sure why this is missing. It might be on purpose (due to a bug in the app) or by mistake. I don't know, but it should be fixed asap as it breaks the user experience if you receive the QR-Code on your mobile device.

## Steps to reproduce the issue
Please use a QR-Code and extract the URL out of it. Open the URL in the Browser.
Current behavior: The Appstore opens ... 

## Expected behaviour
CWA should open and import the rapid test data.

## Possible Fix
Add the required file `apple-app-site-association` on the web-site that is used for `s.coronawarn.app`. That's it.
I don't know whether the app is capable of loading the data. But the code looks capable of doing so.

## Additional context
Our test center does not allow bookings on site. We expect that bookings will be done by the costomer online. Therefore we do not provide the QR-Code when the user enters the test center. We provide the QR-Code via mail if the test result is uploaded to the CWA-Backend. Users of mobile phone currently have to print the QR-Code and scan it afterwards what is a big bummer.

---
 Internal Tracking ID: [EXPOSUREAPP-7379](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7379)
 Internal Tracking ID: [EXPOSUREAPP-7359](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7359)

**Comment by eilers** [comment]
> @eilers Did you take a look at https://github.com/corona-warn-app/cwa-event-landingpage/tree/main/src/well-known?
> There is a file in there called `apple-app-site-association`.

Yes, but i cannot download it. It seems not be available:
```bash
wget --no-check-certificate --quiet \
  --method GET \
  --timeout=0 \
  --header '' \
   'https://s.coronawarn.app/apple-app-site-association'
```
This only returns a 404 and not the file:

```
<html>

<head>
	<title>404 Not Found</title>
</head>

<body>
	<center>
		<h1>404 Not Found</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>

</html>
```

**Comment by thomasaugsten** [comment]
Please try the correct url
https://s.coronawarn.app/.well-known/apple-app-site-association

**Comment by Ein-Tim** [comment]
@eilers 

Okay, but still the redirect works (scanning a QR-Code for an event created with https://www.coronawarn.app/en/eventregistration/):

https://user-images.githubusercontent.com/67682506/119335834-26a9b980-bc8d-11eb-918a-54028aa16260.mp4

The same should apply to RAT, I'll check and come back to you.

**Comment by Ein-Tim** [comment]
I made an appointment at dm for an Rapid Antigen Test (as described in https://www.coronawarn.app/en/blog/2021-05-11-how-to-rapid-test-integration/) and everything worked as expected:

https://user-images.githubusercontent.com/67682506/119336758-4beaf780-bc8e-11eb-8ba0-a278190edfac.mp4

Maybe there is a misconfiguration on your side? 
Also note what @thomasaugsten said in https://github.com/corona-warn-app/cwa-event-landingpage/issues/22#issuecomment-844991193.

**Comment by eilers** [comment]
Thanks for your reply. The interesting question is now, whether your Link "Zur Corona-Warn-App" does work on the iphone and will open the CWA-App or the App-Store?
This is the case I'm talking about. If you scan the QR-Code with a QR-Code-Reading app from the Appstore, you will see that this does not work, too..

**Comment by eilers** [comment]
> Please try the correct url
> https://s.coronawarn.app/.well-known/apple-app-site-association

Can you please tell me, why the sub directory ".well-known" is supported by Apple? I do not see this in any documentation. This is only a valid subdirectory for Android. Afaik the file must be in the root..

**Comment by Ein-Tim** [comment]
@eilers 

> The interesting question is now, whether your Link "Zur Corona-Warn-App" does work on the iphone and will open the CWA-App or the App-Store?

As you can see in the video [here](https://github.com/corona-warn-app/cwa-event-landingpage/issues/22#issuecomment-846954234), the link opens the Corona-Warn-App.

> This is the case I'm talking about. If you scan the QR-Code with a QR-Code-Reading app from the Appstore, you will see that this does not work, too

And this is a problem on Apples side, I think. See https://github.com/corona-warn-app/cwa-event-landingpage/issues/22#issuecomment-844991193

**Comment by dsarkar** [comment]
@eilers We have several reports in the stores with similar issues. Which browser do you use? Does scanning with the native camera work in your case?

**Comment by thomasaugsten** [comment]
@eilers You can find this in all documentation from Apple

https://developer.apple.com/documentation/xcode/supporting-associated-domains
https://developer.apple.com/library/archive/qa/qa1919/_index.html
https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

**Comment by Ein-Tim** [comment]
Please see https://github.com/corona-warn-app/cwa-website/issues/1300 for a report of an Android user.
Seems like he's using Firefox and the website displays that he has to use Google Chrome.

**Comment by eilers** [comment]
> @eilers We have several reports in the stores with similar issues. Which browser do you use? Does scanning with the native camera work in your case?

The behavior on iOS is completely weird.. 
1. If embed the URL into a mail and click on it: The CWA Opens and imports the code. ✔️
2. If I use the iOS-Camera app: The CWA Opens and imports the code. ✔️
2. If I use a QR-Code reader from the App-Store (for instance https://apps.apple.com/de/app/qr-code-scanner/id483336864 ) and presse open, I will jump into the App-Store. 💥
3. If I paste the URL into Safari, I will jump into the App-Store 💥

I'm completely confused about that. But I come down to the decision that this seems somehow be an iOS-Issue and not an issue of the CWA? Frustrating..

**Comment by Ein-Tim** [comment]
> If I use a QR-Code reader from the App-Store (for instance apps.apple.com/de/app/qr-code-scanner/id483336864 ) and presse open, I will jump into the App-Store. 💥

This is especially confusing. Using the QR-Code reader you posted the link to, I have this behavior:

https://user-images.githubusercontent.com/67682506/119656311-d49e9a80-be2a-11eb-8f6d-7cf3a0808413.mp4

As you can see, the CWA says the QR-Code is not valid, but when scanning it with the CWA itself or with the native camera, everything works.

**Comment by dsarkar** [comment]
@eilers Can you reproduce this issue on several iPhone devices?

**Comment by dsarkar** [comment]
@eilers Actually I can confirm your observations from your comment https://github.com/corona-warn-app/cwa-event-landingpage/issues/22#issuecomment-848693290.

**Comment by dsarkar** [comment]
Regarding Android devices it might be system settings, preventing that the app is opened, see comment https://github.com/corona-warn-app/cwa-event-landingpage/issues/23#issuecomment-848765157

**Comment by eilers** [comment]
> @eilers Can you reproduce this issue on several iPhone devices?

Yes. I can confirm that the same behaviour can be reproduced on other iOS-Devices and with other QR-Code scanner apps.
All running on iOS V14.5 btw.

**Comment by Ein-Tim** [comment]
Has this been fixed/improved with #27?

**Comment by eilers** [comment]
Can be considered as fixed.

**Comment by dsarkar** [comment]
Hi @eilers @Ein-Tim Thanks for contributing here. Best wishes, DS 

---
Corona-Warn-App Open Source Team
