### ISSUE TITLE
Change from #30 was not deployed

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-event-landingpage#32]
## Where to find the issue
EN: https://e.coronawarn.app/en/
DE: https://e.coronawarn.app/de/

## Describe the issue
It seems like the change I did in #30 was never deployed to e.coronawarn.app or s.coronawarn.app.

## Suggested change
The [README](https://github.com/corona-warn-app/cwa-event-landingpage#readme) [says](https://github.com/corona-warn-app/cwa-event-landingpage#updating-the-landing-page):

---

### Updating the landing page

Any direct commits and merged pull requests will automatically trigger follow-up actions to build and deploy the changes to [e.coronawarn.app](https://e.coronawarn.app) and [s.coronawarn.app](https://s.coronawarn.app). The respective [GitHub Actions](https://github.com/features/actions) are available in the [.github/workflows](https://github.com/corona-warn-app/cwa-event-landingpage/tree/main/.github/workflows) directory of this repository.

---

This seems to be either out of date or was never true, as in https://github.com/corona-warn-app/cwa-event-landingpage/actions I can only find the [Build Page](https://github.com/corona-warn-app/cwa-event-landingpage/actions/workflows/build.yml) workflow, which is only the GitHub action for the check which runs on every commit in this repo. It is, however, not the workflow deploying the changes. 

So I suggest to add a workflow, similar to the one which can be found in the https://github.com/corona-warn-app/cwa-website repository, which deploys the changes merged into main here, to the PROD server.

cc @dsarkar @thomasaugsten & @christianneu

**Comment by Ein-Tim** [comment]
@dsarkar Will you be able to look at this soon?

**Comment by dsarkar** [comment]
@Ein-Tim Will come back to you, thanks for the ping!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I didn't know about this point as I don't follow this repository on a regular basis. Thank you for the pointer in https://github.com/corona-warn-app/cwa-website/issues/2098#issuecomment-984696982.

It should be clear how this web content is deployed, then the question about the use of the right node version could be looked at. 

Perhaps the original site content was deployed manually and there is no mechanism in place to sync any updates into production?

**Comment by Ein-Tim** [comment]
@MikeMcC399

> Perhaps the original site content was deployed manually and there is no mechanism in place to sync any updates into production?

Yes, I guess so. However, this would contradict what is written in the README.md file.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> > Perhaps the original site content was deployed manually and there is no mechanism in place to sync any updates into production?
> 
> Yes, I guess so. However, this would contradict what is written in the README.md file.

The [README.md#updating-the-landing-page](https://github.com/corona-warn-app/cwa-event-landingpage/blob/main/README.md#updating-the-landing-page) says:

### "Updating the landing page

Any direct commits and merged pull requests will automatically trigger follow-up actions to build and deploy the changes to [e.coronawarn.app](https://e.coronawarn.app) and [s.coronawarn.app](https://s.coronawarn.app). The respective [GitHub Actions](https://github.com/features/actions) are available in the [.github/workflows](.github/workflows) directory of this repository."

so yes, it seems the documentation describes the desired state, however this does not correspond to what [.github/workflows](.github/workflows) actually contains. 

[.github/workflows/build.yml](https://github.com/corona-warn-app/cwa-event-landingpage/blob/main/.github/workflows/build.yml) is the only script to be found in [.github/workflows](.github/workflows). There is no `deploy-master.yml` script or anything similar. As the name suggests, `build.yml` only builds the website. It does not deploy it anywhere.

**Comment by thomasaugsten** [comment]
It is not planned to deploy this part automatically

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay, thanks. So in the future, after a PR is merged, someone will deploy the change manually? 

Can you do this for #30 and the updated copyright year?

**Comment by thomasaugsten** [comment]
The complete main branch will be deployed but it is a more complex process

**Comment by thomasaugsten** [comment]
Deployment is done
