### ISSUE TITLE
Missing social media links for landing pages

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-event-landingpage#35]
## Where to find the issue

- https://e.coronawarn.app/ relating to the Event Landing Page
- https://s.coronawarn.app/ relating to the Rapid Antigen Test Landing Page

## Describe the issue

The footers of the websites:
- https://e.coronawarn.app/
- https://s.coronawarn.app/

are no longer aligned to the footer of the website:
- https://www.coronawarn.app/

The footers of https://e.coronawarn.app/ and https://s.coronawarn.app/ are missing the:
1. Link to Social Media https://www.coronawarn.app/en/community/#social-media
2. Link to Twitter https://twitter.com/coronawarnapp
3. Link to Instagram https://www.instagram.com/rki_fuer_euch/

---
Footer of https://e.coronawarn.app/ and https://s.coronawarn.app/

![s coronawarn app](https://user-images.githubusercontent.com/66998419/148643834-943a2975-4c37-4f32-bfdd-7a0c4b7bc590.jpg)

---
Footer of https://www.coronawarn.app/

![coronawarn app](https://user-images.githubusercontent.com/66998419/148643838-13c54538-834e-44c8-86c2-04eeb209ca4d.jpg)

## Suggested change

Update the footers of the websites:
- https://e.coronawarn.app/
- https://s.coronawarn.app/

to display the same as the footer of the website:
- https://www.coronawarn.app/

including update to the latest Copyright year.

See in particular PR https://github.com/corona-warn-app/cwa-website/pull/2284 "Add social media icons and community section".

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for pointing this out.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Do you plan to provide a PR for this? Else I could do it 🙂

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I was not planning to provide a PR because first the issue about how this repository gets deployed needs to be solved. See your issue https://github.com/corona-warn-app/cwa-event-landingpage/issues/32.

Unless this other issue is solved no change here in the repository would cause a change to the website.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

You're right, I forgot!

Enjoy the weekend!

**Comment by MikeMcC399** [comment]
@dsarkar 

What are the thoughts about making this change?

I believe that the website is only displayed if the user doesn't have the app installed, so probably it will not be seen often.

It would however be more consistent to use the same footer as on the main website.

**Comment by genericmueller** [comment]
FYI: I just opened a CR for that and will bring it in production soon.

**Comment by genericmueller** [comment]
I have a feature branch right now for testing it on all (4) ENVs but in the end deployment will be done from the main branch, sure.

**Comment by genericmueller** [comment]
@Ein-Tim Hmm, I think I mixed something up here. Sorry. I have an internal branch for our deployment, but not in this repo. This repo here is only used to be part of a Docker image, which will then be deployed by us... But for now, the latest Image represents only the footer year changes as far as I see, not more... So someone needs to accept here the latest PRs and based on that create a new Docker image. Only then am I able to apply them to the Cluster.

**Comment by Ein-Tim** [comment]
@genericmueller Right, currently the issue from @MikeMcC399 was not address with a PR here yet. Currently the last merged PR was #33 (updating the copyright year).

So what needs to be done is:
1. Create a PR addressing this issue (@MikeMcC399 will you do this?)
2. Create a new Docker Image
3. You deploy the changes

FYI @dsarkar

**Comment by MikeMcC399** [comment]
@genericmueller / @Ein-Tim 

I suggest to look at PR https://github.com/corona-warn-app/cwa-website/pull/2284 from cwa-website and pick the changes which apply here. @brifemu was the author.

I wasn't planning to submit a PR myself for this.

**Comment by genericmueller** [comment]
@Ein-Tim / @MikeMcC399 
I'm just trying to figure out, who's responsible for this topic. Seems to be someone from SAP, @thomasaugsten ?

**Comment by dsarkar** [comment]
@genericmueller We can provide and merge PRs. Concerning the social media in the footer, we will try by tomorrow to have a PR ready. Anything else?

**Comment by svengabr** [comment]
@genericmueller I did add the footer changes to the `main` branch. Are you able to build the docker image and push it to the container registry or do you need someone to take care of it?

**Comment by genericmueller** [comment]
@svengabr Theoretically, I can also build the image, but it is the responsibility of my colleagues. It must first be checked and approved. The image is built through their build pipeline and is then pushed to the registry. After that, a deployment has to be planned and our environments have to go through to production :) Unfortunately, this is the normal way even with these minor adjustments.

**Comment by thomasaugsten** [comment]
I will trigger the normal deployment process

**Comment by MikeMcC399** [comment]
@svengabr 
I suggest to re-open this issue until the changes are deployed.

**Comment by MikeMcC399** [comment]
Noting the comment from @thomasaugsten in https://github.com/corona-warn-app/cwa-event-landingpage/issues/32#issuecomment-1036025016 "Deployment is done" the social media links on the footers of:

- https://e.coronawarn.app/ relating to the Event Landing Page
- https://s.coronawarn.app/ relating to the Rapid Antigen Test Landing Page

are now updated and showing as follows:

![image](https://user-images.githubusercontent.com/66998419/153580707-58074141-b1b0-47ea-9aee-77f327cdd045.png)

So, now closing this issue as resolved.
