### ISSUE TITLE
Enable Dependabot alerts

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-event-landingpage#56]
It seems that Dependabot alerts are not enabled on this repository, unlike on cwa-website where a lot of the code came from.

Since the npm versions are generally older here than on cwa-website, I would expect to see auto-generated PRs suggested to fix security vulnerabilities, however there are none.

I suggest to enable Dependabot alerts here too (GitHub Settings > Code Security & Analysis).

**Comment by brianebeling** [comment]
Thanks for your suggestion @MikeMcC399. We will have a look internally.
---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Seems like they have now been enabled!
