### ISSUE TITLE
References to TAN Hotline in footer

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-event-landingpage#66]
## Where to find the issue
Footer of all pages on [e.coronawarn.app](https://e.coronawarn.app/), [p.coronawarn.app](https://p.coronawarn.app/) & [s.coronawarn.app](https://s.coronawarn.app/) "Hotline TAN"

## Describe the issue
References to the TAN Hotline in the footer do not say that the hotline will be discontinued.

## Suggestion
Remove the "Hotline TAN" paragraph on 01. Feb 2023.

## References
[coronawarn.app/en/blog/2023-01-18-cwa-3-0](https://www.coronawarn.app/en/blog/2023-01-18-cwa-3-0/) says "... the operation of the verification hotline will be discontinued as of 31.01.2023."

## Related issue
- https://github.com/corona-warn-app/cwa-website/issues/3331

---
Internal Tracking ID: [EXPOSUREAPP-14643](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14643)

**Comment by Ein-Tim** [comment]
@dsarkar & @MikeMcC399 

What would you think about a PR removing the dates from both this repositories code & cwa-websites code? I'd also adjust the relevant tests so that they don't fail.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the suggestion, we will discuss this internally, Internal Tracking ID: [EXPOSUREAPP-14643](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14643). Makes sense.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> What would you think about a PR removing the dates from both this repositories code & cwa-websites code? I'd also adjust the relevant tests so that they don't fail.

Where are you seeing dates in this repository (https://github.com/corona-warn-app/cwa-event-landingpage)? There hasn't been any commit here since last year.

Regarding the cwa-website, I suggest to carry out the discussion in that repository. I don't see any urgency however as the presence of the date and the planned recorded message ensure that users are fully informed.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Sorry for not being clear. I meant to propose the following:

- remove hotline information from the footer of the websites which code is hosted in this repository
- remove hotline information (& the newly added shutdown date) from the website https://coronawarn.app

As @dsarkar already opened an internal ticket for this suggestion, I will leave the issue here and not follow-up in the cwa-website repository, as information from the JIRA ticket will be provided to this GitHub issue. If there is further, cwa-website specific discussion needed, we can continue in a seperate issue there.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks again for bringing our attention to this issue. Indeed, the hotline telephone Numbers should be removed in the footer. Do you want to provide a pull request?

**Comment by Ein-Tim** [comment]
@dsarkar 

For sure! PRs follow later today!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, very much appreciated. I understand you will look also into the cypress test or you'd prefer if we do this?

**Comment by Ein-Tim** [comment]
@dsarkar 

I will look into it, but can't guarantee that I will be able to keep them working correctly. But as far as I see, it's only this test: https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hotline.cy.js that needs changing.

**Comment by Ein-Tim** [comment]
Hey there @dsarkar,

I provided two PRs:
- https://github.com/corona-warn-app/cwa-event-landingpage/pull/67 for this repository
- https://github.com/corona-warn-app/cwa-website/pull/3356 for the cwa-website repository

I also adapted the cypress tests myself!
