### ISSUE TITLE
redirect http to https

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-event-landingpage#8]
## Where to find the issue
http://e.coronawarn.app

## Describe the issue
If you, for any reason, enter the URI in a browser manually without "https:", the server does not respond.

## Suggested change
Redirect requests from http to https.

But actually I also wanted to tell hi to @svengabr ! I didn't hear from you for a while, and it's nice to find you here still full of activity. Hope you're fine!

**Comment by vaubaehn** [comment]
It's now working. Issue can be closed.
How fast was this?!

**Comment by svengabr** [comment]
> But actually I also wanted to tell hi to @svengabr ! I didn't hear from you for a while, and it's nice to find you here still full of activity. Hope you're fine!

@vaubaehn That's nice to hear! I am there all the time but acting more from the background :-)
