### ISSUE TITLE
Logo should redirect to coronawarn.app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-event-landingpage#9]
## Feature description

When clicking on the logo in the top left corner or in the footer it would be nice if the main page www.coronawarn.app would be opened.

## Problem and motivation
Users who want to find out more about the Corona-Warn-App maybe return to this page while waiting for their download to be finished. Then it would be nice if they could directly go to the main page via the logo.

## Is this something you're interested in working on

I'd like to but not sure yet wether I'm able to.

**Comment by svengabr** [comment]
Hey @Ein-Tim,

> I'd like to but not sure yet wether I'm able to.

since we put this repository public yesterday, you should be able to create pull requests if you like to.

The structure is the same as the cwa-website project so you should be familiar with it already! :-)

Have a great day

**Comment by Ein-Tim** [comment]
@svengabr 

Thanks, now I also see the option to create PRs, this wasn't there yet yesterday somehow.

I would have to modify https://github.com/corona-warn-app/cwa-event-landingpage/blob/main/src/partials/header.html & https://github.com/corona-warn-app/cwa-event-landingpage/blob/main/src/partials/footer.html.

**Comment by svengabr** [comment]
@Ein-Tim 

not `header.html`, instead, use this file:
https://github.com/corona-warn-app/cwa-event-landingpage/blob/main/src/partials/global-nav.html

Footer is correct.

**Comment by Ein-Tim** [comment]
Thank you! I'll see wether I can do this 👍

**Comment by Ein-Tim** [comment]
@svengabr Could you take a look at #10?
